### ISSUE TITLE
Release gem version 1.4.1 please

### ISSUE THREAD

**Issue by knightq** [caarlos0/maskedinput-rails#3]
I've seen that code has been upgraded to the latest stable version of maskedinput js (1.4.1), but the gem has not yet been deployed on Rubygem (the [last one](https://rubygems.org/gems/maskedinput-rails/) is on version 1.4.0))

Thank you!

**Comment by caarlos0** [comment]
Done, thanks!

Sorry for the delay, I haven't see the issue before somehow..
